// Generated by build-apps-script.mjs. Edit apps-script-split/*.gs instead.

// ---- 01_Config.gs ----
const SPREADSHEET_ID = "1Q8o3xDW17Db2eNDu-r7b--uevIMgGg9uVOBiMskfB1Q";

const SHEETS = {
  STUDENTS: "Students",
  RECORDS: "Records",
  STUDENT_RECORDS: "StudentRecords",
};

const STUDENT_HEADERS = ["year", "school", "grade", "studentId", "number", "name", "active", "createdAt"];

const RECORD_HEADERS = [
  "recordKey",
  "savedAt",
  "year",
  "school",
  "grade",
  "studentId",
  "number",
  "name",
  "stage",
  "attempt",
  "entryId",
  "practicedAt",
  "accuracy",
  "duration",
  "complete",
  "source",
];
const RECORD_DURATION_COLUMN = RECORD_HEADERS.indexOf("duration") + 1;

const STUDENT_RECORD_HEADERS = [
  "studentKey",
  "year",
  "school",
  "grade",
  "studentId",
  "updatedAt",
  "version",
  "recordsJson",
];

const CACHE_VERSION = "v2";
const CACHE_TTL = {
  STUDENT_ROWS: 300,
  SCHOOLS: 600,
  GRADES: 600,
  STUDENTS: 300,
  RECORDS: 300,
  RECORD_ROW: 1800,
};

// ---- 02_Routes.gs ----
function doGet(event) {
  const params = event.parameter || {};
  const result = handleRequest_(params);
  return output_(result, params.callback);
}

function doPost(event) {
  const params = event.parameter || {};
  const body = event.postData && event.postData.contents ? JSON.parse(event.postData.contents) : {};
  const result = handleRequest_(Object.assign({}, params, body));
  return output_(result);
}

function handleRequest_(params) {
  try {
    const action = params.action || "bootstrap";

    if (action === "setup") {
      ensureSheets_();
      ensureStudentIds_();
      return ok_({ message: "ready" });
    }
    if (action === "bootstrap") return ok_({ students: listStudents_() });
    if (action === "schools") return ok_(getSchoolSummaries_());
    if (action === "grades") return ok_(getGrades_(params.year, params.school));
    if (action === "students") return ok_(getStudentsByScope_(params.year, params.school, params.grade));
    if (action === "studentRecords") {
      return ok_(getStudentRecords_(params.year, params.school, params.grade, params.studentId));
    }
    if (action === "records") {
      return ok_({ records: getStudentRecords_(params.year, params.school, params.grade, params.studentId).records });
    }
    if (action === "saveRecord") {
      return ok_({ record: saveRecord_(parsePayload_(params.payload)) });
    }
    if (action === "clearRecord") {
      const cleared = clearRecord_(params.year, params.school, params.grade, params.studentId, params.entryId);
      return ok_({ cleared: true, records: cleared.records, version: cleared.version, updatedAt: cleared.updatedAt });
    }

    return fail_("unknown action");
  } catch (error) {
    return fail_(error.message || String(error));
  }
}

// ---- 03_Students.gs ----
function listStudents_() {
  const sheet = getSheet_(SHEETS.STUDENTS, STUDENT_HEADERS);
  const rows = readObjects_(sheet, STUDENT_HEADERS);
  const changedRows = [];

  const students = rows
    .map((row, index) => {
      if (!row.name || !row.school || !row.grade) return null;

      if (!row.studentId) {
        row.studentId = "S-" + Utilities.getUuid().slice(0, 8);
        changedRows.push({ rowNumber: index + 2, studentId: row.studentId });
      }

      if (String(row.active || "TRUE").toUpperCase() === "FALSE") return null;

      return {
        year: String(row.year || new Date().getFullYear()),
        school: String(row.school || ""),
        grade: String(row.grade || ""),
        studentId: String(row.studentId || ""),
        number: String(row.number || ""),
        name: String(row.name || ""),
      };
    })
    .filter(Boolean);

  for (const change of changedRows) {
    sheet.getRange(change.rowNumber, STUDENT_HEADERS.indexOf("studentId") + 1).setValue(change.studentId);
  }

  students.sort((a, b) => {
    if (a.year !== b.year) return Number(b.year) - Number(a.year);
    if (a.school !== b.school) return a.school.localeCompare(b.school);
    if (a.grade !== b.grade) return Number(a.grade) - Number(b.grade);
    const an = Number(a.number);
    const bn = Number(b.number);
    if (!isNaN(an) && !isNaN(bn) && an !== bn) return an - bn;
    return a.name.localeCompare(b.name);
  });

  return students;
}

function ensureStudentIds_() {
  listStudents_();
}

function getSchoolSummaries_() {
  const cacheKey = cacheKey_("schools");
  const cached = cacheGet_(cacheKey);
  if (cached) return cached;

  const rows = readStudentValues_();
  const map = {};
  rows.forEach((row) => {
    if (!isActiveStudentRow_(row)) return;
    const year = normalizeYear_(row[0]);
    const school = String(row[1] || "").trim();
    if (!school) return;
    const key = year + "\u0000" + school;
    if (!map[key]) map[key] = { year: year, school: school, count: 0 };
    map[key].count += 1;
  });

  const result = {
    schools: Object.keys(map)
      .map((key) => map[key])
      .sort((a, b) => Number(b.year) - Number(a.year) || a.school.localeCompare(b.school)),
    generatedAt: new Date().toISOString(),
  };
  cachePut_(cacheKey, result, CACHE_TTL.SCHOOLS);
  return result;
}

function getGrades_(year, school) {
  require_(year, "year");
  require_(school, "school");
  year = String(year).trim();
  school = String(school).trim();
  const cacheKey = cacheKey_("grades", year, school);
  const cached = cacheGet_(cacheKey);
  if (cached) return cached;

  const counts = {};
  readStudentValues_().forEach((row) => {
    if (!isActiveStudentRow_(row)) return;
    if (normalizeYear_(row[0]) !== year || String(row[1] || "").trim() !== school) return;
    const grade = String(row[2] || "").trim();
    if (!grade) return;
    counts[grade] = (counts[grade] || 0) + 1;
  });

  const result = {
    year: year,
    school: school,
    grades: Object.keys(counts)
      .map((grade) => ({ grade: grade, count: counts[grade] }))
      .sort((a, b) => Number(a.grade) - Number(b.grade) || a.grade.localeCompare(b.grade)),
  };
  cachePut_(cacheKey, result, CACHE_TTL.GRADES);
  return result;
}

function getStudentsByScope_(year, school, grade) {
  require_(year, "year");
  require_(school, "school");
  require_(grade, "grade");
  year = String(year).trim();
  school = String(school).trim();
  grade = String(grade).trim();
  const cacheKey = cacheKey_("students", year, school, grade);
  const cached = cacheGet_(cacheKey);
  if (cached) return cached;

  const students = readStudentValues_()
    .filter(
      (row) =>
        isActiveStudentRow_(row) &&
        normalizeYear_(row[0]) === year &&
        String(row[1] || "").trim() === school &&
        String(row[2] || "").trim() === grade &&
        String(row[3] || "").trim() &&
        String(row[5] || "").trim(),
    )
    .map((row) => ({
      studentId: String(row[3]).trim(),
      number: String(row[4] || "").trim(),
      name: String(row[5]).trim(),
    }))
    .sort((a, b) => {
      const an = Number(a.number);
      const bn = Number(b.number);
      if (!isNaN(an) && !isNaN(bn) && an !== bn) return an - bn;
      return a.name.localeCompare(b.name);
    });

  const result = { year: year, school: school, grade: grade, students: students };
  cachePut_(cacheKey, result, CACHE_TTL.STUDENTS);
  return result;
}

function readStudentValues_() {
  const cacheKey = cacheKey_("student-rows");
  const cached = cacheGet_(cacheKey);
  if (cached && Array.isArray(cached.rows)) return cached.rows;
  const sheet = requireSheet_(SHEETS.STUDENTS);
  const lastRow = sheet.getLastRow();
  const rows = lastRow < 2 ? [] : sheet.getRange(2, 1, lastRow - 1, STUDENT_HEADERS.length).getValues();
  cachePut_(cacheKey, { rows: rows }, CACHE_TTL.STUDENT_ROWS);
  return rows;
}

function isActiveStudentRow_(row) {
  return String(row[6] === "" ? "TRUE" : row[6]).toUpperCase() !== "FALSE";
}

function normalizeYear_(value) {
  return String(value || new Date().getFullYear()).trim();
}

// ---- 04_Records.gs ----
function listRecords_(year, school, grade, studentId) {
  return getStudentRecords_(year, school, grade, studentId).records;
}

function getStudentRecords_(year, school, grade, studentId) {
  validateStudentScope_(year, school, grade, studentId);
  const studentKey = makeStudentKey_(year, school, grade, studentId);
  const cacheKey = cacheKey_("records", studentKey);
  const cached = cacheGet_(cacheKey);
  if (cached) return cached;
  const stored = readStudentRecordRow_(studentKey);
  if (stored) {
    cachePut_(cacheKey, stored, CACHE_TTL.RECORDS);
    return stored;
  }
  const legacyRecords = listLegacyRecords_(year, school, grade, studentId);
  const result = { studentKey: studentKey, updatedAt: "", version: 0, records: legacyRecords };
  if (Object.keys(legacyRecords).length) {
    const migrated = writeStudentRecordRow_(studentKey, year, school, grade, studentId, legacyRecords, 1);
    cachePut_(cacheKey, migrated, CACHE_TTL.RECORDS);
    return migrated;
  }
  cachePut_(cacheKey, result, CACHE_TTL.RECORDS);
  return result;
}

function saveRecord_(payload) {
  validateStudentScope_(payload.year, payload.school, payload.grade, payload.studentId);
  require_(payload.entryId, "entryId");
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) throw new Error("다른 저장 작업이 진행 중입니다. 잠시 후 다시 시도해주세요.");
  try {
    const studentKey = makeStudentKey_(payload.year, payload.school, payload.grade, payload.studentId);
    const stored = readStudentRecordRow_(studentKey);
    const records = stored ? stored.records : listLegacyRecords_(payload.year, payload.school, payload.grade, payload.studentId);
    const duration = normalizeDuration_(payload.duration);
    const accuracy = payload.accuracy === undefined ? "" : String(payload.accuracy);
    records[payload.entryId] = {
      datetime: String(payload.datetime || ""),
      accuracy: accuracy,
      duration: accuracy ? duration : "",
    };
    const result = writeStudentRecordRow_(
      studentKey,
      payload.year,
      payload.school,
      payload.grade,
      payload.studentId,
      records,
      (stored ? stored.version : 0) + 1,
    );
    appendLegacyAudit_(payload, result.updatedAt, "github-pages-v2");
    cachePut_(cacheKey_("records", studentKey), result, CACHE_TTL.RECORDS);
    return {
      recordKey: makeRecordKey_(payload.year, payload.school, payload.grade, payload.studentId, payload.entryId),
      savedAt: result.updatedAt,
      complete: Boolean(payload.datetime && accuracy !== "" && duration),
      version: result.version,
      records: result.records,
    };
  } finally {
    lock.releaseLock();
  }
}

function clearRecord_(year, school, grade, studentId, entryId) {
  validateStudentScope_(year, school, grade, studentId);
  require_(entryId, "entryId");
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(10000)) throw new Error("다른 저장 작업이 진행 중입니다. 잠시 후 다시 시도해주세요.");
  try {
    const studentKey = makeStudentKey_(year, school, grade, studentId);
    const stored = readStudentRecordRow_(studentKey);
    const records = stored ? stored.records : listLegacyRecords_(year, school, grade, studentId);
    delete records[entryId];
    const result = writeStudentRecordRow_(
      studentKey,
      year,
      school,
      grade,
      studentId,
      records,
      (stored ? stored.version : 0) + 1,
    );
    appendLegacyAudit_({ year: year, school: school, grade: grade, studentId: studentId, entryId: entryId }, result.updatedAt, "clear-v2");
    cachePut_(cacheKey_("records", studentKey), result, CACHE_TTL.RECORDS);
    return result;
  } finally {
    lock.releaseLock();
  }
}

function validateStudentScope_(year, school, grade, studentId) {
  require_(year, "year");
  require_(school, "school");
  require_(grade, "grade");
  require_(studentId, "studentId");
}

function makeStudentKey_(year, school, grade, studentId) {
  return [year, school, grade, studentId].map((value) => encodeURIComponent(String(value).trim())).join("|");
}

function readStudentRecordRow_(studentKey) {
  const sheet = requireSheet_(SHEETS.STUDENT_RECORDS);
  const rowNumber = findStudentRecordRow_(sheet, studentKey);
  if (!rowNumber) return null;
  const row = sheet.getRange(rowNumber, 1, 1, STUDENT_RECORD_HEADERS.length).getValues()[0];
  let records;
  try {
    records = row[7] ? JSON.parse(String(row[7])) : {};
  } catch (error) {
    throw new Error("학생 기록 데이터가 손상되었습니다: " + studentKey);
  }
  return { studentKey: String(row[0]), updatedAt: String(row[5] || ""), version: Number(row[6] || 0), records: records };
}

function writeStudentRecordRow_(studentKey, year, school, grade, studentId, records, version) {
  const sheet = requireSheet_(SHEETS.STUDENT_RECORDS);
  const rowNumber = findStudentRecordRow_(sheet, studentKey) || sheet.getLastRow() + 1;
  const updatedAt = Utilities.formatDate(new Date(), Session.getScriptTimeZone(), "yyyy-MM-dd'T'HH:mm:ss");
  sheet.getRange(rowNumber, 1, 1, STUDENT_RECORD_HEADERS.length).setValues([[
    studentKey, String(year), String(school), String(grade), String(studentId), updatedAt,
    Number(version || 0), JSON.stringify(records || {}),
  ]]);
  cachePut_(cacheKey_("record-row", studentKey), { rowNumber: rowNumber }, CACHE_TTL.RECORD_ROW);
  return { studentKey: studentKey, updatedAt: updatedAt, version: Number(version || 0), records: records || {} };
}

function findStudentRecordRow_(sheet, studentKey) {
  const cached = cacheGet_(cacheKey_("record-row", studentKey));
  if (cached && cached.rowNumber > 1 && cached.rowNumber <= sheet.getLastRow()) {
    if (String(sheet.getRange(cached.rowNumber, 1).getValue()) === studentKey) return cached.rowNumber;
  }
  if (sheet.getLastRow() < 2) return 0;
  const match = sheet.getRange(2, 1, sheet.getLastRow() - 1, 1)
    .createTextFinder(studentKey).matchEntireCell(true).findNext();
  const rowNumber = match ? match.getRow() : 0;
  if (rowNumber) cachePut_(cacheKey_("record-row", studentKey), { rowNumber: rowNumber }, CACHE_TTL.RECORD_ROW);
  return rowNumber;
}

function listLegacyRecords_(year, school, grade, studentId) {
  const sheet = requireSheet_(SHEETS.RECORDS);
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return {};
  const rows = sheet.getRange(2, 1, lastRow - 1, RECORD_HEADERS.length).getValues();
  const records = {};
  rows.forEach((row) => {
    if (String(row[2]) === String(year) && String(row[3]) === String(school) &&
        String(row[4]) === String(grade) && String(row[5]) === String(studentId) && row[10]) {
      const accuracy = row[12] === "" ? "" : String(row[12]);
      records[String(row[10])] = {
        datetime: String(row[11] || ""), accuracy: accuracy,
        duration: accuracy ? normalizeDuration_(row[13]) : "",
      };
    }
  });
  return records;
}

function appendLegacyAudit_(payload, savedAt, source) {
  try {
    const sheet = requireSheet_(SHEETS.RECORDS);
    const duration = normalizeDuration_(payload.duration);
    const accuracy = payload.accuracy === undefined ? "" : payload.accuracy;
    sheet.appendRow([
      makeRecordKey_(payload.year, payload.school, payload.grade, payload.studentId, payload.entryId),
      savedAt, payload.year, payload.school, payload.grade, payload.studentId,
      payload.number || "", payload.name || "", payload.stage || "", payload.attempt || "", payload.entryId,
      payload.datetime || "", accuracy, duration, payload.datetime && accuracy !== "" && duration ? "Y" : "N", source,
    ]);
  } catch (error) {
    // StudentRecords is authoritative; a compatibility audit failure is non-fatal.
  }
}

// ---- 05_Sheets.gs ----
function ensureSheets_() {
  const students = getSheet_(SHEETS.STUDENTS, STUDENT_HEADERS);
  const records = getSheet_(SHEETS.RECORDS, RECORD_HEADERS);
  const studentRecords = getSheet_(SHEETS.STUDENT_RECORDS, STUDENT_RECORD_HEADERS);
  formatSheet_(students, STUDENT_HEADERS.length);
  formatSheet_(records, RECORD_HEADERS.length);
  formatSheet_(studentRecords, STUDENT_RECORD_HEADERS.length);
}

function requireSheet_(name) {
  const sheet = getSpreadsheet_().getSheetByName(name);
  if (!sheet) throw new Error(name + " 시트가 없습니다. setup을 먼저 실행해주세요.");
  return sheet;
}

function getSheet_(name, headers) {
  const spreadsheet = getSpreadsheet_();
  let sheet = spreadsheet.getSheetByName(name);
  if (!sheet) sheet = spreadsheet.insertSheet(name);

  const firstRow = sheet.getRange(1, 1, 1, headers.length).getValues()[0];
  const empty = firstRow.every((value) => value === "");
  if (empty) {
    sheet.getRange(1, 1, 1, headers.length).setValues([headers]);
  } else {
    headers.forEach((header, index) => {
      if (firstRow[index] !== header) sheet.getRange(1, index + 1).setValue(header);
    });
  }
  return sheet;
}

function getSpreadsheet_() {
  if (SPREADSHEET_ID) return SpreadsheetApp.openById(SPREADSHEET_ID);
  return SpreadsheetApp.getActiveSpreadsheet();
}

function readObjects_(sheet, headers) {
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return [];
  const values = sheet.getRange(2, 1, lastRow - 1, headers.length).getValues();
  return values.map((row) => {
    const object = {};
    headers.forEach((header, index) => {
      object[header] = row[index];
    });
    return object;
  });
}

function findRecordRow_(sheet, recordKey) {
  const lastRow = sheet.getLastRow();
  if (lastRow < 2) return 0;
  const values = sheet.getRange(2, 1, lastRow - 1, 1).getValues();
  for (let index = 0; index < values.length; index += 1) {
    if (String(values[index][0]) === recordKey) return index + 2;
  }
  return 0;
}

function formatSheet_(sheet, width) {
  sheet.setFrozenRows(1);
  sheet.getRange(1, 1, 1, width).setFontWeight("bold").setBackground("#E9F7F7");
  sheet.autoResizeColumns(1, width);
}

// ---- 06_Utils.gs ----
function makeRecordKey_(year, school, grade, studentId, entryId) {
  return [year, school, grade, studentId, entryId].map((value) => String(value).trim()).join("|");
}

function parsePayload_(payload) {
  if (!payload) return {};
  if (typeof payload === "object") return payload;
  return JSON.parse(payload);
}

function require_(value, name) {
  if (value === undefined || value === null || String(value).trim() === "") {
    throw new Error(name + " is required");
  }
}

function normalizeDuration_(value) {
  if (value === undefined || value === null || value === "") return "";

  if (typeof value === "number" && isFinite(value) && value >= 0 && value < 1) {
    return sheetTimeSerialToDuration_(value);
  }

  if (Object.prototype.toString.call(value) === "[object Date]" && !isNaN(value.getTime())) {
    const minutes = value.getHours();
    const seconds = value.getMinutes();
    return pad2_(minutes) + ":" + pad2_(seconds);
  }

  const text = String(value).trim();
  if (!text) return "";

  const dateTimeMatch = text.match(/\b(\d{1,2}):(\d{2})(?::\d{2})?\b/);
  if (dateTimeMatch && /GMT|UTC|\d{4}|[A-Za-z]{3}/.test(text)) {
    const minutes = Number(dateTimeMatch[1]);
    const seconds = Number(dateTimeMatch[2]);
    if (minutes >= 0 && seconds >= 0 && seconds < 60) return pad2_(minutes) + ":" + pad2_(seconds);
  }

  const parts = text.split(":");
  if (parts.length === 2) {
    const minutes = Number(parts[0]);
    const seconds = Number(parts[1]);
    if (Number.isInteger(minutes) && Number.isInteger(seconds) && minutes >= 0 && seconds >= 0 && seconds < 60) {
      return pad2_(minutes) + ":" + pad2_(seconds);
    }
  }

  if (parts.length === 3) {
    const hours = Number(parts[0]);
    const minutes = Number(parts[1]);
    const seconds = Number(parts[2]);
    if (
      Number.isInteger(hours) &&
      Number.isInteger(minutes) &&
      Number.isInteger(seconds) &&
      hours >= 0 &&
      minutes >= 0 &&
      minutes < 60 &&
      seconds >= 0 &&
      seconds < 60
    ) {
      return pad2_(hours * 60 + minutes) + ":" + pad2_(seconds);
    }
  }

  return "";
}

function pad2_(value) {
  return String(value).padStart(2, "0");
}

function sheetTimeSerialToDuration_(value) {
  const totalMinutes = Math.round(value * 24 * 60);
  const minutes = Math.floor(totalMinutes / 60);
  const seconds = totalMinutes % 60;
  return pad2_(minutes) + ":" + pad2_(seconds);
}

function output_(result, callback) {
  const json = JSON.stringify(result);
  if (callback) {
    const safeCallback = String(callback).replace(/[^\w.$]/g, "");
    return ContentService.createTextOutput(safeCallback + "(" + json + ");").setMimeType(
      ContentService.MimeType.JAVASCRIPT,
    );
  }
  return ContentService.createTextOutput(json).setMimeType(ContentService.MimeType.JSON);
}

function ok_(data) {
  return {
    ok: true,
    data: data || {},
  };
}

function fail_(message) {
  return {
    ok: false,
    error: message || "error",
  };
}

// ---- 07_Cache.gs ----
function cacheKey_(namespace) {
  const parts = Array.prototype.slice.call(arguments, 1).map((value) => String(value || "").trim());
  const digest = parts.length ? digestKey_(parts.join("\u0000")) : "all";
  return ["trb", namespace, digest, CACHE_VERSION].join(":");
}

function digestKey_(value) {
  const bytes = Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, value, Utilities.Charset.UTF_8);
  return bytes
    .slice(0, 12)
    .map((byte) => (byte < 0 ? byte + 256 : byte).toString(16).padStart(2, "0"))
    .join("");
}

function cacheGet_(key) {
  try {
    const value = CacheService.getScriptCache().get(key);
    return value ? JSON.parse(value) : null;
  } catch (error) {
    return null;
  }
}

function cachePut_(key, value, ttl) {
  try {
    CacheService.getScriptCache().put(key, JSON.stringify(value), ttl);
  } catch (error) {
    // Cache failures must not make the API fail.
  }
}

function cacheRemove_(key) {
  try {
    CacheService.getScriptCache().remove(key);
  } catch (error) {
    // Cache failures must not make the API fail.
  }
}

// ---- 08_Migration.gs ----
function migrateRecordsToStudentRecords() {
  ensureSheets_();
  const source = requireSheet_(SHEETS.RECORDS);
  const lastRow = source.getLastRow();
  if (lastRow < 2) return { students: 0, sourceRows: 0, migratedRecords: 0, duplicatesResolved: 0, invalidRows: 0 };
  const values = source.getRange(2, 1, lastRow - 1, RECORD_HEADERS.length).getValues();
  const groups = {};
  let invalidRows = 0;
  let duplicatesResolved = 0;
  values.forEach((row) => {
    const year = String(row[2] || "").trim();
    const school = String(row[3] || "").trim();
    const grade = String(row[4] || "").trim();
    const studentId = String(row[5] || "").trim();
    const entryId = String(row[10] || "").trim();
    if (!year || !school || !grade || !studentId || !entryId) { invalidRows += 1; return; }
    const studentKey = makeStudentKey_(year, school, grade, studentId);
    if (!groups[studentKey]) groups[studentKey] = { year: year, school: school, grade: grade, studentId: studentId, entries: {} };
    const existing = groups[studentKey].entries[entryId];
    const savedAt = String(row[1] || "");
    if (existing) { duplicatesResolved += 1; if (existing.savedAt > savedAt) return; }
    const accuracy = row[12] === "" ? "" : String(row[12]);
    groups[studentKey].entries[entryId] = {
      savedAt: savedAt,
      record: { datetime: String(row[11] || ""), accuracy: accuracy, duration: accuracy ? normalizeDuration_(row[13]) : "" },
    };
  });
  let migratedRecords = 0;
  Object.keys(groups).forEach((studentKey) => {
    const group = groups[studentKey];
    const legacyRecords = {};
    Object.keys(group.entries).forEach((entryId) => { legacyRecords[entryId] = group.entries[entryId].record; migratedRecords += 1; });
    const existing = readStudentRecordRow_(studentKey);
    const records = Object.assign({}, legacyRecords, existing ? existing.records : {});
    writeStudentRecordRow_(studentKey, group.year, group.school, group.grade, group.studentId, records,
      Math.max(existing ? existing.version : 0, 1));
    cacheRemove_(cacheKey_("records", studentKey));
  });
  return {
    students: Object.keys(groups).length, sourceRows: values.length, migratedRecords: migratedRecords,
    duplicatesResolved: duplicatesResolved, invalidRows: invalidRows,
  };
}
